<?xml version="1.0" encoding="utf-8"?>
<Database Name="bookmark" Class="FavorsTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\bookmark.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bookmarkConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AppraiseOfWebSite" Member="AppraiseOfWebSite">
    <Type Name="AppraiseOfWebSite">
      <Column Name="Href" Type="System.String" DbType="VarChar(500) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Titles" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TitlesCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TagsCount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FavorLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="QueryFrequency" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RemarksCount" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Favors" Member="Favors">
    <Type Name="Favors">
      <Column Name="FavorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Href" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tag" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ReferSite" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SubmitTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FavorLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Privacy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VisitCount" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LastVisit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>