//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerspectiveDemo.Pages.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DpiScaling {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DpiScaling() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerspectiveDemo.Pages.Strings.DpiScaling", typeof(DpiScaling).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply scale factor.
        /// </summary>
        internal static string ApplyScaleFactor {
            get {
                return ResourceManager.GetString("ApplyScaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ruler should measure 15 cm..
        /// </summary>
        internal static string DefaultRulerSize {
            get {
                return ResourceManager.GetString("DefaultRulerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        internal static string DpiUnitName {
            get {
                return ResourceManager.GetString("DpiUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not, enter the diagonal screen size, or move the slider until the ruler measures 15 cm..
        /// </summary>
        internal static string HowToSetScale {
            get {
                return ResourceManager.GetString("HowToSetScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical DPI.
        /// </summary>
        internal static string PhysicalDPI {
            get {
                return ResourceManager.GetString("PhysicalDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen independent scale factor to apply.
        /// </summary>
        internal static string ScaleFactorToApply {
            get {
                return ResourceManager.GetString("ScaleFactorToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen diagonal size (inches).
        /// </summary>
        internal static string ScreenSize {
            get {
                return ResourceManager.GetString("ScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System DPI configuration.
        /// </summary>
        internal static string SystemDpiText {
            get {
                return ResourceManager.GetString("SystemDpiText", resourceCulture);
            }
        }
    }
}
