//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GreenYellow")]
        public global::System.Drawing.Color PositionSetToGetConvexHullColor {
            get {
                return ((global::System.Drawing.Color)(this["PositionSetToGetConvexHullColor"]));
            }
            set {
                this["PositionSetToGetConvexHullColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ConvexHullPositionSetInSpecificLevelColor {
            get {
                return ((global::System.Drawing.Color)(this["ConvexHullPositionSetInSpecificLevelColor"]));
            }
            set {
                this["ConvexHullPositionSetInSpecificLevelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color LinePositionSetInSpecificLevelColor {
            get {
                return ((global::System.Drawing.Color)(this["LinePositionSetInSpecificLevelColor"]));
            }
            set {
                this["LinePositionSetInSpecificLevelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 0, 128")]
        public global::System.Drawing.Color ChildPositionSetInSpecificLevelOfConvexHullColor {
            get {
                return ((global::System.Drawing.Color)(this["ChildPositionSetInSpecificLevelOfConvexHullColor"]));
            }
            set {
                this["ChildPositionSetInSpecificLevelOfConvexHullColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RealConvexHullColor {
            get {
                return ((global::System.Drawing.Color)(this["RealConvexHullColor"]));
            }
            set {
                this["RealConvexHullColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color BottonLevelPositionSetColor {
            get {
                return ((global::System.Drawing.Color)(this["BottonLevelPositionSetColor"]));
            }
            set {
                this["BottonLevelPositionSetColor"] = value;
            }
        }
    }
}
